assignment/assignment/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from . import settings, views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', views.HomePage.as_view(), name='home'),
    path('search/', include('searches.urls')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='allproducts'),
]

assignment/searches/urls.py
from django.urls import path
from . import views

app_name = 'searches'
urlpatterns = [
    path('', views.SearchProductListView.as_view(), name='query'),
    path('ref/', views.Filter.as_view(), name='refine'),
]

assignment/searches/models.py
from django.db import models

# Create your models here.

assignment/searches/views.py
from django.shortcuts import render
from django.views.generic import ListView
from products.models import Product, Category
from tags.models import Tag
from django.shortcuts import Http404
from django.db.models import Avg, Max, Min, Q

# Create your views here.

_query = ''
class SearchProductListView(ListView):
    template_name = 'searches/view.html'

    def get_context_data(self, *args, **kwargs):
        context = super(SearchProductListView, self).get_context_data(*args, **kwargs)
        request = self.request
        content = request.GET.get('q')

        if len(content.split())>1:
            content = content.split()
            for value in content:
                obj = Category.objects.filter(Q(title__icontains=value)|Q(description__icontains=value))
                if obj.first():
                    if obj.first().title=='Mobile':
                        context['content']='mobile'
                        context['android']='Android'
                        context['iOS'] = 'iOS'
                        break

        else:
                obj = Category.objects.filter(Q(title__icontains=content)|Q(description__icontains=content))
                if obj.first():
                    if obj.first().title=='Mobile':
                        context['content'] = 'mobile'
                        context['android']='Android'
                        context['iOS'] = 'iOS'

        return context


    def get_queryset(self, *args, **kwargs):
         request = self.request
         query = request.GET.get('q', None) # request.GET is python dictionary.
         if query is not None:
            #Implemented this in models ProductModelManager(custom))
             return Product.objects.search(query)
         else:
             return Product.objects.none()


class Filter(ListView):
    template_name = 'searches/view.html'

    def get_queryset(self, *args, **kwargs):
        request = self.request
        _query = request.GET.get('prev')

        if 'low_price' in request.GET:
            low_price = request.GET.get('low_price')
            max_price = request.GET.get('high_price')

            if 'Android' in request.GET:
                _query = 'android'
            if 'iOS' in request.GET:
                _query = 'iOS'

            if low_price =='':
                low_price=0
            if max_price=='':
                if len(_query.split())>1:
                    q = _query.split()

                    for value in q:
                        print(value)
                        print('looking in ', _query)
                        obj = Category.objects.filter(Q(title__icontains=_query)|Q(description__icontains=_query))
                        max_price = obj.first()
                        print(max_price)
                        max_price = max_price.products.aggregate(Max('price'))
                        print(max_price)


                        if max_price is not None:
                            print('filter price 2 is found and is ', max_price)
                            break

                else:
                    print('looking in ', _query)
                    obj = Category.objects.filter(Q(title__icontains=_query)|Q(description__icontains=_query))
                    max_price = obj.first()
                    print(max_price)
                    max_price = max_price.products.aggregate(Max('price'))
                    print(max_price)
                    #
                    if  len(max_price) != 1:
                        max_price=Product.objects.search(_query).aggregate(Max('price'))

                    max_price = max_price.get('price__max')
                    print(max_price)

            my_products=Product.objects.search(_query).filter_price(low_price=low_price, high_price=max_price)
            print('My products after applying filter are', my_products)
            return my_products

        if 'Android' in request.GET:
            return Product.objects.search('android')
        elif 'iOS' in request.GET:
            return Product.objects.search('iOS')

assignment/searches/templates/searches/view.html
{% extends "base.html" %}
{% block content %}
  {% if request.GET.q or request.GET.Android or request.GET.iOS %}
    <div class="col-12" py=4>
        Results for <b>{{request.GET.q}}</b> <br> <br>
      {% if content %}
      <div class="col-xs-6">

        <div class="container text-left">
          <h6>Refine</h6>
          <p>Mobile Phone Operating System</p>
          <form action="{% url 'searches:refine' %}" method="get">
            <label class="checkbox">
              <input type="checkbox" id="{{android}}" name="{{android}}"value="1">{{android}}
            </label>
            <label class="checkbox">
              <input type="checkbox" id="{{iOS}}" name="{{iOS}}"value="2">{{iOS}}
            </label>
            <br>
            <input type="submit" class="btn btn-primary btn-sm btn-outline-dark"name="" value="Refine!">
          </form>
        </div
    </div>
{%endif%}



        {# <input type="text" name="" class="form-control col-lg-6 mx-auto"  value="Filter by"> #}
        <div class="container mr-auto"><br>
          <p>Price Range</p>
          <form method="get" action="{% url 'searches:refine' %}">

            <span>₹</span>
            <input class="form-input col-3"type="text" maxlength="9" id="low_price" placeholder="Min" name="low_price"
            class=" input-sm col-lg-2" aria-label="Min">

            <span>₹</span>
            <input class="form-input col-3"type="text" maxlength="9" id="high_price" placeholder="Max" name="high_price"
            class="input-sm col-lg-2" aria-label="Max">
            <input type="hidden" name="prev" id="prev"value="{{request.GET.q}}">
            <input class="btn btn-primary" type="submit" name="" value="Go">
          </form>


        </div>
      </div>
      <hr>

  {% else %}

  {% endif %}
    {% if request.GET.low_price %}<p class="mb-3"> <em>Filtered Products!</em> </p> {% endif %}



      <div class="row">
        {% for object in object_list %}
          <div class="col">
            {% include "products/snippets/card.html" with instance=object%} <br>
          </div>
        {% endfor %}
      </div>
{% endblock %}