assignment/assignment/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from . import settings, views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', views.HomePage.as_view(), name='home'),
    path('search/', include('searches.urls')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='allproducts'),
]

assignment/templates/snippets/navbar.html
{% url 'products:allproducts' as allprodcuts_url %}
<!--request.path is enabled by default-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container">
  <a class="navbar-brand" href="{% url 'home' %}">{% if base_name %}{{base_name}} {% else %} Aditya eCommerce{% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item {% if request.path == allprodcuts_url %}active{% endif %}">
        <a class="nav-link" href="{{allprodcuts_url}}">Products</a>
      </li>

    </ul>

    {% include "searches/snippets/search-form.html" %}




  </div>
</div>
</nav>
      <!--{ include "search/snippets/search-form.html" }-->